### ISSUE TITLE
Can't intsall theme

### ISSUE THREAD

**Issue by thelaycon** [jyygithub/hugo-theme-onelou#4]
I can't seem to find a way to install the theme. 

I get the following error when I uncomment the 'theme' option in config.yaml:

>> error: add site dependencies: load resources: loading templates: "/home/tobi/okun/themes/hugo-theme-onelou/layouts/partials/pagination.html:11:1": parse failed: template: partials/pagination.html:11: unclosed action

**Comment by jyygithub** [comment]
I have tested it just now, I didn't find any error. So I hope you can give me more details.
